name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 8
    - name: Setup Web Drivers  
      uses: nanasess/setup-chromedriver@v1
    - name: Build and Test
      run: | 
        export DISPLAY=:99
        sbt -Dwebdriver.chrome.driver=chromedriver -v +test 